# Permalinks
permalink:           pretty

# Setup
title:               Nick Thomas
tagline:             A blog where science has been known to happen
url:
paginate:            2
baseurl:             ""

# Assets
#
# We specify the directory for Jekyll so we can use @imports.
sass:
  sass_dir:          _sass
  style:            :compressed

# About/contact
author:
  name:              Nick Thomas
  url:
  email:

# Custom vars
version:             2.0.0
github:
  repo:              

# Gems
gems:
  - jekyll-paginate
  - jekyll-gist

# Page List
pages_list:
  About: '/about'
  Archive: '/archive'
  Feed: '/index.html'
